### ISSUE TITLE
Whats the highest value you have tested with the snore function?

### ISSUE THREAD

**Issue by gavinlyonsrepo** [connornishijima/TinySnore#8]
Hi 

Thank you for library.

Whats the highest value you have tested with the snore function?
I want something to "sleep" for 18 hrs I put in  64800000ms and it never work up?

Regards

**Comment by connornishijima** [comment]
I haven't yet tested something like an 18-hour sleep, I wonder what went wrong! I'll look into this.

*In the mean time, it's possible that a loop of smaller sleeps like this could work instead:*

```c
for( uint8_t hours = 0; hours < 18; hours++ ){ // -- Sleep 1 hour at a time
  snore( 1000 * 60 * 60 ); // ---------------------- 1 hour in ms
}
```

**Comment by gavinlyonsrepo** [comment]
Update:
It was a battery issue on my device. I only checked one of them initially.  When I checked all one was dead. It must have been the cold outside. I will delete issue presently. 

Sorry.

**Comment by connornishijima** [comment]
Dang, good to know! Feel free to update me here if anything changes.
